### ISSUE TITLE
Training issue

### ISSUE THREAD

**Issue by jiangxinhao2020** [Zongwei97/PopNet#1]
Thank you for your excellent work. In the manuscript, the GPU is V100 and the image size is 512. My GPU is GV100,32GB, but why can I only set the image to 384 and the batchsize to 4.

**Comment by Zongwei97** [comment]
Hello,

Thanks for your interest in our work.

Your case is quite weird to me.
I just tried the default setting with size=512 and bs=8 on my V100 with 32G. 
During training, it takes around 30G.

With 384, you should even be capable of increasing the bs ...
