### ISSUE TITLE
 I find a code error when training

### ISSUE THREAD

**Issue by dongzhi128128** [Zongwei97/PopNet#2]
Traceback (most recent call last):
  File "train.py", line 192, in <module>
    train(train_loader, model, optimizer, epoch, save_path)
  File "train.py", line 108, in train
    loss7 = structure_loss(thresh, gts)
UnboundLocalError: local variable 'thresh' referenced before assignment

I don't understand or the code is something wrong.

By the way, in loss.py,  get_gradient and cos are undefined, but I can find them in other py, it's ok.

**Comment by Zongwei97** [comment]
Hi, 

Thanks a lot for your interest in our work and for pointing out the errors ...
I wanted to restructure the code, and apparently, it led to some errors...

Indeed, the cos in loss.py can be found in train.py
The thresh in train.py can be found several lines later. You can move the line loss7 just before the line of total loss.

I have checked and updated all of them.

Thanks again

**Comment by dongzhi128128** [comment]
Your paper attracted me very much and I am very grateful for your efficiency in solving my problem
