### ISSUE TITLE
IF "Source-free Depth Network" Code exists? 

### ISSUE THREAD

**Issue by ziskazuo** [Zongwei97/PopNet#4]
Hi sir, thanks for your great work!
  Here is my question, IF "Source-free Depth Network" mentioned in your paper  is just an assumption of Network Model Architecture, cause i can't find any code about this (or DPT model you use) in project. This makes me confused.
THANKS FOR YOUR ANSWER!

**Comment by Zongwei97** [comment]
Hi,

Thanks for your interest in our work.
The DPT code is used to generate the pseudo depth, if there is no GT depth, which is the case for COD.
As mentioned in the paper, we used the [official application](https://github.com/isl-org/DPT) and further improved the depth quality by applying [refinement method](https://github.com/compphoto/BoostingMonocularDepth).
The generated depth for COD can be directly downloaded here ([Training](https://drive.google.com/file/d/1z903IE3fQderj_ngOi1rIsnTDhT7NHDS/view?usp=sharing)/[Testing](https://drive.google.com/file/d/1xd_Pe4oQZJqHX5NHSswwGk7AoaeH38eQ/view?usp=sharing))
